function b = b_twolegs(in1,in2,in3)
%B_TWOLEGS
%    B = B_TWOLEGS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    21-Nov-2024 19:07:59

dth1 = in1(5,:);
dth2 = in1(6,:);
dth3 = in1(7,:);
dth4 = in1(8,:);
g = in3(19,:);
l_AC = in3(17,:);
l_A_m3 = in3(13,:);
l_B_m2 = in3(12,:);
l_C_m4 = in3(14,:);
l_OA = in3(15,:);
l_OB = in3(16,:);
l_O_m1 = in3(11,:);
m1 = in3(1,:);
m2 = in3(2,:);
m3 = in3(3,:);
m4 = in3(4,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
tau3 = in2(3,:);
tau4 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
t2 = sin(th1);
t3 = sin(th2);
t4 = sin(th3);
t5 = sin(th4);
t6 = th1+th2;
t7 = th3+th4;
t8 = dth1.^2;
t9 = dth3.^2;
t10 = l_OA.*t2;
t11 = l_OA.*t4;
t12 = sin(t6);
t13 = sin(t7);
mt1 = [tau1+dth2.*(dth1.*l_AC.*l_C_m4.*m4.*t3.*2.0+dth2.*l_AC.*l_C_m4.*m4.*t3+dth1.*l_AC.*l_OA.*m4.*t3.*2.0+dth2.*l_AC.*l_OA.*m4.*t3+dth1.*l_A_m3.*l_OA.*m3.*t3.*2.0+dth2.*l_A_m3.*l_OA.*m3.*t3+dth1.*l_B_m2.*l_OB.*m2.*t3.*2.0+dth2.*l_B_m2.*l_OB.*m2.*t3)-g.*m2.*(l_B_m2.*t12+l_OB.*t2)-g.*m3.*(t10+l_A_m3.*t12)-g.*m4.*(t10+l_AC.*t12+l_C_m4.*t2)-g.*l_O_m1.*m1.*t2];
mt2 = [tau2+dth2.*(dth1.*l_AC.*l_C_m4.*m4.*t3+dth1.*l_AC.*l_OA.*m4.*t3+dth1.*l_A_m3.*l_OA.*m3.*t3+dth1.*l_B_m2.*l_OB.*m2.*t3)-g.*l_AC.*m4.*t12-g.*l_A_m3.*m3.*t12-g.*l_B_m2.*m2.*t12-l_AC.*l_C_m4.*m4.*t3.*t8-l_AC.*l_OA.*m4.*t3.*t8-l_A_m3.*l_OA.*m3.*t3.*t8-l_B_m2.*l_OB.*m2.*t3.*t8-dth1.*dth2.*l_AC.*l_C_m4.*m4.*t3-dth1.*dth2.*l_AC.*l_OA.*m4.*t3-dth1.*dth2.*l_A_m3.*l_OA.*m3.*t3-dth1.*dth2.*l_B_m2.*l_OB.*m2.*t3];
mt3 = [tau3+dth4.*(dth3.*l_AC.*l_C_m4.*m4.*t5.*2.0+dth4.*l_AC.*l_C_m4.*m4.*t5+dth3.*l_AC.*l_OA.*m4.*t5.*2.0+dth4.*l_AC.*l_OA.*m4.*t5+dth3.*l_A_m3.*l_OA.*m3.*t5.*2.0+dth4.*l_A_m3.*l_OA.*m3.*t5+dth3.*l_B_m2.*l_OB.*m2.*t5.*2.0+dth4.*l_B_m2.*l_OB.*m2.*t5)-g.*m2.*(l_B_m2.*t13+l_OB.*t4)-g.*m3.*(t11+l_A_m3.*t13)-g.*m4.*(t11+l_AC.*t13+l_C_m4.*t4)-g.*l_O_m1.*m1.*t4];
mt4 = [tau4+dth4.*(dth3.*l_AC.*l_C_m4.*m4.*t5+dth3.*l_AC.*l_OA.*m4.*t5+dth3.*l_A_m3.*l_OA.*m3.*t5+dth3.*l_B_m2.*l_OB.*m2.*t5)-g.*l_AC.*m4.*t13-g.*l_A_m3.*m3.*t13-g.*l_B_m2.*m2.*t13-l_AC.*l_C_m4.*m4.*t5.*t9-l_AC.*l_OA.*m4.*t5.*t9-l_A_m3.*l_OA.*m3.*t5.*t9-l_B_m2.*l_OB.*m2.*t5.*t9-dth3.*dth4.*l_AC.*l_C_m4.*m4.*t5-dth3.*dth4.*l_AC.*l_OA.*m4.*t5-dth3.*dth4.*l_A_m3.*l_OA.*m3.*t5-dth3.*dth4.*l_B_m2.*l_OB.*m2.*t5];
b = [mt1;mt2;mt3;mt4];
end
