function Corr_Joint_Sp = Corr_leg(in1,in2)
%Corr_leg
%    Corr_Joint_Sp = Corr_leg(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Nov-2024 15:01:33

dth1 = in1(7,:);
dth2 = in1(8,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(3,:);
th2 = in1(4,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t6 = dth1.^2;
t7 = dth2.^2;
t8 = l_AC.*l_C_m4.*m4;
t9 = l_AC.*l_OA.*m4;
t10 = l_A_m3.*l_OA.*m3;
t11 = l_B_m2.*l_OB.*m2;
t12 = cos(t5);
t13 = l_OA.*t3;
t14 = sin(t5);
t18 = t8+t9+t10+t11;
t15 = dth2.*l_AC.*t14.*4.0;
t16 = dth2.*l_A_m3.*t14.*4.0;
t17 = dth2.*l_B_m2.*t14.*4.0;
mt1 = [-dth1.*((m2.*(t17+dth1.*(l_B_m2.*t14+l_OB.*t3).*4.0))./2.0+(m3.*(t16+dth1.*(t13+l_A_m3.*t14).*4.0))./2.0+(m4.*(t15+dth1.*(t13+l_AC.*t14+l_C_m4.*t3).*4.0))./2.0+dth1.*l_O_m1.*m1.*t3)-dth2.*((m4.*(t15+dth1.*l_AC.*t14.*4.0))./2.0+(m3.*(t16+dth1.*l_A_m3.*t14.*4.0))./2.0+(m2.*(t17+dth1.*l_B_m2.*t14.*4.0))./2.0);l_AC.*m4.*t6.*t12.*2.0+l_AC.*m4.*t7.*t12.*2.0+l_A_m3.*m3.*t6.*t12.*2.0+l_A_m3.*m3.*t7.*t12.*2.0+l_B_m2.*m2.*t6.*t12.*2.0+l_B_m2.*m2.*t7.*t12.*2.0+l_C_m4.*m4.*t2.*t6.*2.0+l_OA.*m3.*t2.*t6.*2.0+l_OB.*m2.*t2.*t6.*2.0+l_OA.*m4.*t2.*t6.*2.0+l_O_m1.*m1.*t2.*t6+dth1.*dth2.*l_AC.*m4.*t12.*4.0+dth1.*dth2.*l_A_m3.*m3.*t12.*4.0+dth1.*dth2.*l_B_m2.*m2.*t12.*4.0;-dth2.*t4.*t18.*(dth1.*2.0+dth2)];
mt2 = [t4.*t6.*t18];
Corr_Joint_Sp = [mt1;mt2];
end
