function E = energy_leg(in1,in2)
%ENERGY_LEG
%    E = ENERGY_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Nov-2024 15:01:32

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
Ir = in2(9,:);
N = in2(10,:);
dth1 = in1(7,:);
dth2 = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
g = in2(19,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(3,:);
th2 = in1(4,:);
y = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = dth1+dth2;
t5 = th1+th2;
t6 = dth1.^2;
t7 = dx.*2.0;
t8 = dy.*2.0;
t9 = y.*2.0;
t10 = l_C_m4.*t2;
t11 = l_OA.*t2;
t12 = l_OB.*t2;
t13 = cos(t5);
t14 = l_OA.*t3;
t15 = sin(t5);
t16 = -t9;
t17 = t4.^2;
t18 = l_AC.*t13;
t19 = l_A_m3.*t13;
t20 = l_B_m2.*t13;
et1 = (m4.*((t7+dth2.*t18+dth1.*(t10+t11+t18)).^2+(t8+dth1.*(t14+l_AC.*t15+l_C_m4.*t3)+dth2.*l_AC.*t15).^2))./2.0+(m2.*((t7+dth1.*(t12+t20)+dth2.*t20).^2+(t8+dth1.*(l_B_m2.*t15+l_OB.*t3)+dth2.*l_B_m2.*t15).^2))./2.0+(I1.*t6)./2.0+(I4.*t6)./2.0+(I2.*t17)./2.0+(I3.*t17)./2.0+(m3.*((t7+dth1.*(t11+t19)+dth2.*t19).^2+(t8+dth1.*(t14+l_A_m3.*t15)+dth2.*l_A_m3.*t15).^2))./2.0+(m1.*((dx+dth1.*l_O_m1.*t2).^2+(dy+dth1.*l_O_m1.*t3).^2))./2.0+(Ir.*(dth1+N.*dth2).^2)./2.0+g.*m1.*(y-l_O_m1.*t2)-g.*m4.*(t10+t11+t16+t18)+(Ir.*N.^2.*t6)./2.0;
et2 = -g.*m3.*(t11+t16+t19)-g.*m2.*(t12+t16+t20);
E = et1+et2;
end
