function rE = position_foot(in1,in2)
%POSITION_FOOT
%    rE = POSITION_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    11-Nov-2024 13:27:31

l_AC = in2(17,:);
l_DE = in2(18,:);
l_OB = in2(16,:);
th1 = in1(3,:);
th2 = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
rE = [x+l_DE.*t3+l_OB.*t3+l_AC.*sin(t4);y-l_DE.*t2-l_OB.*t2-l_AC.*cos(t4)];
end
