function Grav_Joint_Sp = Grav_twolegs(in1,in2)
%Grav_twolegs
%    Grav_Joint_Sp = Grav_twolegs(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 16:17:34

g = in2(19,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
th4 = in1(6,:);
t2 = sin(th1);
t3 = sin(th3);
t4 = l_AC.*m4;
t5 = l_A_m3.*m3;
t6 = l_B_m2.*m2;
t7 = th1+th2;
t8 = th3+th4;
t9 = l_OA.*t2;
t10 = l_OA.*t3;
t11 = sin(t7);
t12 = sin(t8);
t13 = t4+t5+t6;
Grav_Joint_Sp = [0.0;g.*(m1+m2+m3+m4).*2.0;g.*m2.*(l_B_m2.*t11+l_OB.*t2)+g.*m3.*(t9+l_A_m3.*t11)+g.*m4.*(t9+l_AC.*t11+l_C_m4.*t2)+g.*l_O_m1.*m1.*t2;g.*t11.*t13;g.*m2.*(l_B_m2.*t12+l_OB.*t3)+g.*m3.*(t10+l_A_m3.*t12)+g.*m4.*(t10+l_AC.*t12+l_C_m4.*t3)+g.*l_O_m1.*m1.*t3;g.*t12.*t13];
end
