function dJ2 = jacobian_dot_foot2(in1,in2)
%JACOBIAN_DOT_FOOT2
%    dJ2 = JACOBIAN_DOT_FOOT2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 16:17:34

dth3 = in1(11,:);
dth4 = in1(12,:);
l_AC = in2(17,:);
l_DE = in2(18,:);
l_OB = in2(16,:);
th3 = in1(5,:);
th4 = in1(6,:);
t2 = cos(th3);
t3 = sin(th3);
t4 = th3+th4;
t5 = cos(t4);
t6 = sin(t4);
t7 = dth4.*l_AC.*t5;
t8 = dth4.*l_AC.*t6;
t9 = -t8;
dJ2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t9-dth3.*(l_AC.*t6+l_DE.*t3+l_OB.*t3),t7+dth3.*(l_AC.*t5+l_DE.*t2+l_OB.*t2),t9-dth3.*l_AC.*t6,t7+dth3.*l_AC.*t5],[2,6]);
end
