function keypoints = keypoints_twolegs(in1,in2)
%KEYPOINTS_TWOLEGS
%    KEYPOINTS = KEYPOINTS_TWOLEGS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 16:17:34

l_AC = in2(17,:);
l_DE = in2(18,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
th4 = in1(6,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th1);
t3 = cos(th3);
t4 = sin(th1);
t5 = sin(th3);
t6 = th1+th2;
t7 = th3+th4;
t8 = l_OA.*t2;
t9 = l_OB.*t2;
t10 = l_OA.*t3;
t11 = l_OB.*t3;
t12 = cos(t6);
t13 = cos(t7);
t14 = l_OA.*t4;
t15 = l_OB.*t4;
t16 = l_OA.*t5;
t17 = l_OB.*t5;
t18 = sin(t6);
t19 = sin(t7);
t20 = l_AC.*t12;
t21 = l_AC.*t13;
t22 = l_AC.*t18;
t23 = l_AC.*t19;
t24 = -t8;
t25 = -t9;
t26 = -t10;
t27 = -t11;
t28 = -t20;
t29 = -t21;
keypoints = reshape([x,y,t14+x,t24+y,t15+x,t25+y,t14+t22+x,t24+t28+y,t15+t22+x,t25+t28+y,t15+t22+x+l_DE.*t4,t25+t28+y-l_DE.*t2,t16+x,t26+y,t17+x,t27+y,t16+t23+x,t26+t29+y,t17+t23+x,t27+t29+y,t17+t23+x+l_DE.*t5,t27+t29+y-l_DE.*t3],[2,11]);
end
