function rOE2 = position_foot2(in1,in2)
%POSITION_FOOT2
%    rOE2 = POSITION_FOOT2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 16:17:33

l_AC = in2(17,:);
l_DE = in2(18,:);
l_OB = in2(16,:);
th3 = in1(5,:);
th4 = in1(6,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th3);
t3 = sin(th3);
t4 = th3+th4;
rOE2 = [x+l_DE.*t3+l_OB.*t3+l_AC.*sin(t4);y-l_DE.*t2-l_OB.*t2-l_AC.*cos(t4)];
end
