function PE = potential_energy_twolegs(in1,in2)
%POTENTIAL_ENERGY_TWOLEGS
%    PE = POTENTIAL_ENERGY_TWOLEGS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 16:17:33

g = in2(19,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(3,:);
th2 = in1(4,:);
th3 = in1(5,:);
th4 = in1(6,:);
y = in1(2,:);
t2 = cos(th1);
t3 = cos(th3);
t4 = th1+th2;
t5 = th3+th4;
t10 = -y;
t6 = l_OA.*t2;
t7 = l_OA.*t3;
t8 = cos(t4);
t9 = cos(t5);
PE = g.*m1.*(y-l_O_m1.*t2)+g.*m1.*(y-l_O_m1.*t3)-g.*m2.*(t10+l_B_m2.*t8+l_OB.*t2)-g.*m2.*(t10+l_B_m2.*t9+l_OB.*t3)-g.*m3.*(t6+t10+l_A_m3.*t8)-g.*m3.*(t7+t10+l_A_m3.*t9)-g.*m4.*(t6+t10+l_AC.*t8+l_C_m4.*t2)-g.*m4.*(t7+t10+l_AC.*t9+l_C_m4.*t3);
end
