function dq = qdot_twolegs(in1,in2)
%QDOT_TWOLEGS
%    DQ = QDOT_TWOLEGS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 16:17:33

dth1 = in1(9,:);
dth2 = in1(10,:);
dth3 = in1(11,:);
dth4 = in1(12,:);
dx = in1(7,:);
dy = in1(8,:);
dq = [dx;dy;dth1;dth2;dth3;dth4];
end
