function A = A_twolegs(in1,in2)
%A_twolegs
%    A = A_twolegs(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Nov-2024 14:09:58

I1 = in2(5,:);
I2 = in2(6,:);
I3 = in2(7,:);
I4 = in2(8,:);
Ir = in2(9,:);
N = in2(10,:);
l_AC = in2(17,:);
l_A_m3 = in2(13,:);
l_B_m2 = in2(12,:);
l_C_m4 = in2(14,:);
l_OA = in2(15,:);
l_OB = in2(16,:);
l_O_m1 = in2(11,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th2 = in1(2,:);
th4 = in1(4,:);
t2 = cos(th2);
t3 = cos(th4);
t4 = N.^2;
t5 = l_AC.^2;
t6 = l_A_m3.^2;
t7 = l_B_m2.^2;
t8 = l_C_m4.^2;
t9 = l_OA.^2;
t10 = l_OB.^2;
t11 = l_O_m1.^2;
t12 = Ir.*N;
t22 = l_C_m4.*l_OA.*m4.*2.0;
t13 = Ir.*t4;
t14 = m4.*t5;
t15 = m3.*t6;
t16 = m2.*t7;
t17 = m4.*t8;
t18 = m3.*t9;
t19 = m2.*t10;
t20 = m4.*t9;
t21 = m1.*t11;
t23 = l_AC.*l_C_m4.*m4.*t2;
t24 = l_AC.*l_C_m4.*m4.*t3;
t25 = l_AC.*l_OA.*m4.*t2;
t26 = l_AC.*l_OA.*m4.*t3;
t27 = l_A_m3.*l_OA.*m3.*t2;
t28 = l_A_m3.*l_OA.*m3.*t3;
t29 = l_B_m2.*l_OB.*m2.*t2;
t30 = l_B_m2.*l_OB.*m2.*t3;
t31 = I2+I3+t13+t14+t15+t16;
t32 = I2+I3+t12+t14+t15+t16+t23+t25+t27+t29;
t33 = I2+I3+t12+t14+t15+t16+t24+t26+t28+t30;
A = reshape([I1+I4+Ir+t17+t18+t19+t20+t21+t22+t23.*2.0+t25.*2.0+t27.*2.0+t29.*2.0+t31,t32,0.0,0.0,t32,t31,0.0,0.0,0.0,0.0,I1+I4+Ir+t17+t18+t19+t20+t21+t22+t24.*2.0+t26.*2.0+t28.*2.0+t30.*2.0+t31,t33,0.0,0.0,t33,t31],[4,4]);
end
