function q = q_twolegs(in1,in2)
%Q_TWOLEGS
%    Q = Q_TWOLEGS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Nov-2024 14:09:58

th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
q = [th1;th2;th3;th4];
end
