function dq = qdot_twolegs(in1,in2)
%QDOT_TWOLEGS
%    DQ = QDOT_TWOLEGS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Nov-2024 14:09:58

dth1 = in1(5,:);
dth2 = in1(6,:);
dth3 = in1(7,:);
dth4 = in1(8,:);
dq = [dth1;dth2;dth3;dth4];
end
